name: TradeLens
channels:
  - conda-forge
dependencies:
  # --- Core ---
  - python = 3.11
  - pip
  - tzdata            # time-zone db
  - python-tzdata     # tzinfo shim for pandas/Django
  - packaging         # version parsing

  # --- Web / Django ---
  - django
  - channels
  - daphne
  - asgiref

  # --- Data Science (conda builds exist) ---
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - numba
  - h5py
  - matplotlib
  - seaborn
  - plotly
  - mplfinance

  # --- Jupyter ---
  - jupyterlab
  - notebook

  # --- Databases & Cache ---
  - psycopg2
  - sqlalchemy
  - redis-py        # Python client only

  # --- Async / Task queue ---
  - celery
  - kombu
  - billiard
  - vine

  # --- Utilities ---
  - requests
  - boto3
  - beautifulsoup4
  - lxml
  - pillow
  - pyyaml
  - cryptography

  # --- Pip-only heavyweights & extra deps ---
  - pip:
      - torch==2.2.*       # brings torchvision/torchaudio wheels if CPU-only
      - tensorflow==2.18.*
      - keras==3.*
      - channels-redis     # pure-python wheel
      - -r requirements.txt