name: TradeLens
channels:
  - conda-forge
  - defaults

dependencies:
  # --- Core Environment ---
  - python=3.12
  - pip

  # --- Web & Django Framework ---
  - django
  - channels
  - daphne
  - asgiref
  - channels-redis

  # --- Data Science & Machine Learning ---
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - statsmodels
  - tensorflow
  - keras
  - pytorch
  - torchvision
  - torchaudio
  - tslearn
  - numba
  - h5py

  # --- Database & Caching ---
  - psycopg2
  - sqlalchemy
  - redis-py # Conda package for 'redis'

  # --- Asynchronous & Task Queues ---
  - celery
  - kombu
  - billiard
  - vine

  # --- Jupyter Ecosystem ---
  - jupyterlab
  - notebook

  # --- Plotting & Visualization ---
  - matplotlib
  - seaborn
  - plotly
  - mplfinance

  # --- General Utilities ---
  - boto3
  - requests
  - beautifulsoup4
  - lxml
  - pillow
  - pyyaml
  - cryptography

  # --- Pip Dependencies ---
  - pip:
    - -r requirements.txt