# Generated by Django 5.1 on 2024-10-01 00:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_params', models.JSONField()),
                ('model_weights_dir', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X_features', models.JSONField()),
                ('y_features', models.JSONField()),
                ('sequence_params', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('train_or_test', models.CharField(max_length=10)),
                ('index_range', models.JSONField(default=None)),
                ('pred', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None)),
                ('actual', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None)),
                ('general_metrics', models.JSONField(default=None)),
                ('sequence_metrics', models.JSONField(default=None)),
                ('sequence_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=None, size=None)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_manager.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='trainer',
            name='training_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_manager.trainingsession'),
        ),
    ]
