# Generated by Django 5.1 on 2024-10-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_manager', '0003_alter_evaluation_general_metrics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureset',
            old_name='scaler_condfig',
            new_name='scaler_config',
        ),
    ]
