# Generated by Django 5.1 on 2024-10-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_manager', '0004_rename_scaler_condfig_featureset_scaler_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='feature_sets',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='feature_set_configs',
            field=models.JSONField(default=None, null=True),
        ),
    ]
