# Generated by Django 5.1 on 2025-01-25 21:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityModel',
            fields=[
                ('entity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('attributes', models.JSONField(db_column='attributes', default=dict)),
                ('children_ids', models.JSONField(default=list)),
                ('parent_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyRequest',
            fields=[
                ('entity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strategy_name', models.CharField(max_length=255)),
                ('param_config', models.JSONField(default=dict)),
                ('target_entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('add_to_history', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategy_requests', to='shared_utils.entitymodel')),
                ('parent_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_requests', to='shared_utils.strategyrequest')),
            ],
        ),
    ]
