# Generated by Django 5.1 on 2024-12-11 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training_session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=255)),
                ('strategy_path', models.CharField(max_length=255)),
                ('param_config', models.JSONField(default=dict)),
                ('add_to_history', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_requests', to='shared_utils.strategyrequest')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_requests', to='training_session.trainingsession')),
            ],
        ),
    ]
