# Generated by Django 5.1 on 2024-12-11 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_utils', '0001_initial'),
        ('training_session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyrequest',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategy_requests', to='training_session.trainingsession'),
        ),
    ]
