# Generated by Django 5.1 on 2025-01-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_utils', '0002_alter_strategyrequest_training_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyrequest',
            name='target_entity_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
