# Generated by Django 5.1 on 2025-06-14 16:50

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_utils', '00002_vector_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymodel',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
