# Generated by Django 5.1 on 2025-06-14 16:58

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_utils', '0003_entitymodel_embedding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entitymodel',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='entity_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
