# Generated by Django 5.1 on 2025-01-12 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_utils', '0003_strategyrequest_target_entity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategyrequest',
            name='strategy_path',
        ),
    ]
