# Generated by Django 5.1 on 2025-01-23 00:59

import django.contrib.postgres.fields.jsonb
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_utils', '0004_remove_strategyrequest_strategy_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(db_column='attributes', default=dict)),
                ('children_ids', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('parent_ids', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_path', models.CharField(max_length=255)),
            ],
        ),
    ]
