# Generated by Django 5.1 on 2025-01-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_utils', '0005_entitymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitymodel',
            name='attributes',
            field=models.JSONField(db_column='attributes', default=dict),
        ),
        migrations.AlterField(
            model_name='entitymodel',
            name='children_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='entitymodel',
            name='parent_ids',
            field=models.JSONField(default=list),
        ),
    ]
