# Generated by Django 5.1 on 2025-01-23 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_utils', '0006_alter_entitymodel_attributes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategyrequest',
            name='training_session',
        ),
        migrations.AddField(
            model_name='strategyrequest',
            name='entity_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategy_requests', to='shared_utils.entitymodel'),
        ),
    ]
