# Generated by Django 5.1 on 2025-01-23 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_utils', '0007_remove_strategyrequest_training_session_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitymodel',
            old_name='id',
            new_name='entity_id',
        ),
    ]
