# Generated by Django 5.1 on 2025-01-23 02:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_utils', '0008_rename_id_entitymodel_entity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategyrequest',
            name='id',
        ),
        migrations.AlterField(
            model_name='strategyrequest',
            name='entity_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
