# Generated by Django 5.1 on 2025-01-23 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_utils', '0009_remove_strategyrequest_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategyrequest',
            old_name='entity_model',
            new_name='entity_models',
        ),
        migrations.RenameField(
            model_name='strategyrequest',
            old_name='parent_request',
            new_name='parent_requesst',
        ),
    ]
