# Generated by Django 5.1 on 2025-01-23 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_utils', '0010_rename_entity_model_strategyrequest_entity_models_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategyrequest',
            old_name='entity_models',
            new_name='entity_model',
        ),
        migrations.RenameField(
            model_name='strategyrequest',
            old_name='parent_requesst',
            new_name='parent_request',
        ),
    ]
