# Generated by Django 5.1 on 2024-08-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequenceset_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('feature_dict', models.JSONField()),
                ('timeframe', models.CharField(choices=[('5m', '5m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('4h', '4h'), ('1d', '1d'), ('1w', '1w'), ('1M', '1M')], max_length=3)),
            ],
        ),
    ]
