# Generated by Django 5.1 on 2024-08-23 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequenceset_manager', '0002_featuredict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocksequence',
            name='column_dict',
        ),
    ]
