# Generated by Django 5.1 on 2024-09-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequenceset_manager', '0003_remove_stocksequence_column_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceSetTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('sequence_length', models.IntegerField()),
                ('timeframe', models.CharField(choices=[('5m', '5m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('4h', '4h'), ('1d', '1d'), ('1w', '1w'), ('1M', '1M')], max_length=3)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
