# Generated by Django 5.1 on 2024-09-02 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequenceset_manager', '0004_sequencesettracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequencesettracker',
            old_name='end_date',
            new_name='end_timestamp',
        ),
        migrations.RenameField(
            model_name='sequencesettracker',
            old_name='start_date',
            new_name='start_timestamp',
        ),
    ]
