# Generated by Django 5.1 on 2024-09-08 20:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequenceset_manager', '0005_rename_end_date_sequencesettracker_end_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DatsetType', models.CharField(max_length=10)),
                ('sequence_length', models.IntegerField()),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('metadata', models.JSONField()),
                ('feature_names', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('feature_names', models.JSONField()),
                ('sequence_data', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('sequence_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequenceset_manager.sequenceset')),
            ],
        ),
    ]
