# Generated by Django 5.1 on 2024-09-08 21:10

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequenceset_manager', '0006_sequenceset_sequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequenceset',
            old_name='DatsetType',
            new_name='DatasetType',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='sequence_data',
        ),
        migrations.CreateModel(
            name='FeatureSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequenceset_manager.sequence')),
            ],
        ),
    ]
