# Generated by Django 5.1 on 2024-09-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequenceset_manager', '0007_rename_datsettype_sequenceset_datasettype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequenceset',
            old_name='DatasetType',
            new_name='datasetType',
        ),
    ]
